<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "inventory"
 *
 * Auto generated by Extension Builder 2013-06-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Inventory',
	'description' => 'An example extension for Extbase & Fluid development, presenting a simple inventory management Application.',
	'category' => 'plugin',
	'author' => 'Martin Helmich',
	'author_email' => 'typo3@martin-helmich.de',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'experimental',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>